### ISSUE TITLE
Plans on this package

### ISSUE THREAD

**Issue by strdr4605** [jaing/react-native-places-input#1]
Hi, currently I am using [react-native-google-places-autocomplete](https://github.com/FaridSafi/react-native-google-places-autocomplete) and it has a rich API, but a feature which is missing for Android is [clearButtonMode](https://reactnative.dev/docs/textinput.html#clearbuttonmode) as in iOS. 

The codebase is a mess and it is hard to contribute. Maintainer said that he is working on refactoring (but it may take a long time).

 I would like to know about future plans for this package. Will be more configurations added or it is ok for your case and you don't plan to invest a lot of time on this package?

**Comment by jaing** [comment]
Hi mate - I'm currently using this package in one of my projects and I'm still planing to improve it. Let me know what you need and I may be able to add it even today :). As you see it's a fairly simple component so it takes no time to add new stuff.
