### ISSUE TITLE
Include 'powered by Google` Logo when Showing Predictions

### ISSUE THREAD

**Issue by jparksecurity** [jaing/react-native-places-input#13]
According to [the Google Maps Platform doc](https://developers.google.com/maps/documentation/javascript/places-autocomplete#address_forms), it says that

> Note: When you display predictions from Place Autocomplete, you must include the 'powered by Google' logo. This logo is included in the results list by default, as shown in the above example.

Like the figure below:

![](https://developers.google.com/maps/documentation/javascript/images/places-autocomplete-suggest.png)

So I think it needs to show not only predictions but also the logo.

Thank you!

**Comment by jaing** [comment]
I added two new props:

New configuration props:
* **contentScrollViewBottom** - Custom content at the bottom of scroll view list with results
* **contentScrollViewTop** - Custom content at the bottom of scroll view list with results

you can add any content you like on top or bottom of a list.
