### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by jparksecurity** [jaing/react-native-places-input#14]
Could you add a license?

**Comment by jaing** [comment]
I added two new props:

New configuration props:
* **contentScrollViewBottom** - Custom content at the bottom of scroll view list with results
* **contentScrollViewTop** - Custom content at the bottom of scroll view list with results

you can add any content you like on top or bottom of a list.

**Comment by jparksecurity** [comment]
@jaing I'm not sure if this issue has been addressed.

What I meant was to add the license of this project. Is it MIT? or something else?

**Comment by jaing** [comment]
done!
