### ISSUE TITLE
keyboard doesn't open when clicking on the search bar

### ISSUE THREAD

**Issue by MedDimessi** [jaing/react-native-places-input#17]
![searchwontwork](https://user-images.githubusercontent.com/36376966/79747500-b3a07780-8303-11ea-8c2e-72dee25a6fa7.gif)

**Comment by luismasg** [comment]
Hi. Could you share some of your layout or component composition?
Remember stuff needs to be placed   absolutely over the map

**Comment by jaing** [comment]
Did you enable a hardware keyboard in a simulator?
