### ISSUE TITLE
Overall positioning of list and impact from keyboard

### ISSUE THREAD

**Issue by tylerthedeveloper** [jaing/react-native-places-input#21]
First of all, absolutely love this package, thank you so much.

Impact of Keyboard view: 
- im trying to think aloud what make sense here, but in my case, this field is lower in my screen, so when the suggestions pop up, they come behind the keyboard
- one thing i tried was switching the list to populate above
     - this isnt great and a little hacky, but helps
     - i think having a "top" and "bottom" (where bottom is default) of list would be an easy conditional in the render

Happy to look into a PR for these

**Comment by tylerthedeveloper** [comment]
With regard to first one, maybe my use case is special, but the goal is to programmatically scroll to adjust the size - playing around with the below

//onChangeText={() => scrollRef.current?.scrollToEnd()}
onChangeText={() => scrollRef.current?.scrollTo({y: 2 * contentHeight, animated: true})}

**Comment by jaing** [comment]
If think it should be possible by overriding stylesList. Just position in absolute with bottom equal input height. let me know if that works
