### ISSUE TITLE
Set default value

### ISSUE THREAD

**Issue by tylerthedeveloper** [jaing/react-native-places-input#22]
is this possible?

i'd like have a default address selected

**Comment by bhavya95** [comment]
@tylerthedeveloper you can use textInputProps
`textInputProps={{value: 'default value'}}`

**Comment by tylerthedeveloper** [comment]
@bhavya95 then once you try to change it immediately resets itself because the value is bound to that ...

**Comment by jaing** [comment]
Can you provide more clarification?

**Comment by tylerthedeveloper** [comment]
- i set the value to an item that has state with useState
- I then set that to the value based on your suggestion
- this did preset the value 
- however when i try to edit or click x on the input it resets it back to the original state value

**Comment by tylerthedeveloper** [comment]
All i have is:

```
onSelect={place => setPlace(place))}
textInputProps={{
   autoCorrect: false,
   value: "El Paso, Texas"
}}
```

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/13102536/81859732-b02f9300-9533-11ea-8969-1eb6323fb11e.gif)

**Comment by tylerthedeveloper** [comment]
All I have is 

 const [location, setLocation] = useState();


<PlaceInput
...
onSelect={place => setLocation(place))}
textInputProps={{
   autoCorrect: false,
   value: location || "El Paso, Texas" 
}}
..
/>

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/13102536/81876782-7bcacf80-9551-11ea-9e90-c3bb7bba2974.gif)

**Comment by tylerthedeveloper** [comment]
any thoughts @jaing ?

**Comment by jaing** [comment]
can you try with a query prop?

query: this.props.query || '',

**Comment by tylerthedeveloper** [comment]
so that worked when hardcoded, but I fetch current location (standard) and set it to that, and it never re-renders, even though console.log(currentLocation) will show the correct output

**Comment by jaing** [comment]
Please try 1.1.5. Component now will update a query value on prop change and there is a new config to clear query on palce select
