### ISSUE TITLE
Clear input icon not visible

### ISSUE THREAD

**Issue by 8enSmith** [jaing/react-native-places-input#23]
I am using your nice component in Expo to create an Android app:

               <PlacesInput
                    queryCountries={['uk']}
                    querySession={uuidV4}
                    googleApiKey={GOOGLE_API_KEY as string}
                    requiredCharactersBeforeSearch={3}
                    onSelect={(place) => {
                        const region = {
                            latitude: place.result.geometry.location.lat,
                            longitude: place.result.geometry.location.lng,
                            ...deltas,
                        }
                        setRegion(region)
                        Keyboard.dismiss()
                    }}
                />

It's working well except that the clear input icon (i.e. the cross) is not displayed in the input box.

Do I need to set a property to get this rendered or is this an issue?

**Comment by 8enSmith** [comment]
Ah, I can see on the react-native documentation for [TextInput](https://reactnative.dev/docs/textinput) that the clearButtonMode is an iOS only feature. 

Looks like I am going to need to call the clear method on Android to remove the input value.

**Comment by 8enSmith** [comment]
Doh accidentally closed it after reopening it!

In my previous comment I highlighted that android users will need to call the clear method to clear the input. However I wont have access to that when using your component.

It would be great if a feature was added to clear the input after a value is selected e.g. add a prop called "clearInputOnSelection" or something similar?

**Comment by jaing** [comment]
I added : clearQueryOnSelect
In a near future i will try to add a clear button for every platform.

**Comment by 8enSmith** [comment]
@jaing Nice work. I can confirm that the input is now getting cleared after selection when I run it on an Android device via Expo.
