### ISSUE TITLE
Query could not clear when submit form

### ISSUE THREAD

**Issue by mertaksu** [jaing/react-native-places-input#24]
First of all thanks for being a useful library. I am new in react native maybe i can miss some trips. When a place search after select and submit for input text value could not clear. I am using placeQuery state for keep input value. When i click to button i am setting placeQuery state to empty string but input text could not clear.

query={this.state.placeQuery || ''}
                    googleApiKey={API_KEY}
                    placeHolder="Arazi Lokasyonu"
                    language={'tr'}
                    queryCountries={['tr']}
                    onSelect={place =>  {
                        this.setState({selectedPlaceLat : place.result.geometry.location.lat, selectedPlaceLon: place.result.geometry.location.lat, placeQuery: ''});
                    }}

Submit button function inside

 this.setState({landName: '',placeQuery: '',selectedPlaceLat: '',selectedPlaceLon:'',error:''});

<img width="414" alt="Ekran Resmi 2020-05-18 02 20 29" src="https://user-images.githubusercontent.com/7141261/82162729-5f12fc80-98af-11ea-8a36-fcce676e98c7.png">

**Comment by jaing** [comment]
Please try 1.1.5. Component now will update a query value on prop change and there is a new config to clear query on palce select
