### ISSUE TITLE
Bug when clicking on predictions

### ISSUE THREAD

**Issue by Jeca1801** [jaing/react-native-places-input#3]
Sometimes when i click on a prediction i get an TypeError: undefined is not an object (evaluating 'place.result.formmated_adress') error.. and sometimes it works good

https://gyazo.com/f8603e6ed6f903cd97a548374c59fbfe

**Comment by jaing** [comment]
Can you replicate this query using API directly and post a response here? I will need to validate it and see what API is returning. I.e.

https://maps.googleapis.com/maps/api/place/autocomplete/json?input=110%20Ward&location=40.7128%2C-74.0059&radius=500&types=address&components=country%3ACA%7Ccountry%3AUS&key=YOUR_API_KEY

**Comment by Jeppe90** [comment]
`{
   "predictions" : [
      {
         "description" : "110 Ward Drive, New Rochelle, New York, USA",
         "id" : "3ed4273818378bfea2b2a2ee7b5261a4403533d2",
         "matched_substrings" : [
            {
               "length" : 3,
               "offset" : 0
            },
            {
               "length" : 4,
               "offset" : 4
            }
         ],
         "place_id" : "ChIJzT6wM7OTwokR95iWmndXFP0",
         "reference" : "ChIJzT6wM7OTwokR95iWmndXFP0",
         "structured_formatting" : {
            "main_text" : "110 Ward Drive",
            "main_text_matched_substrings" : [
               {
                  "length" : 3,
                  "offset" : 0
               },
               {
                  "length" : 4,
                  "offset" : 4
               }
            ],
            "secondary_text" : "New Rochelle, New York, USA"
         },
         "terms" : [
            {
               "offset" : 0,
               "value" : "110"
            },
            {
               "offset" : 4,
               "value" : "Ward Drive"
            },
            {
               "offset" : 16,
               "value" : "New Rochelle"
            },
            {
               "offset" : 30,
               "value" : "New York"
            },
            {
               "offset" : 40,
               "value" : "USA"
            }
         ],
         "types" : [ "premise", "geocode" ]
      },
      {
         "description" : "110 Ward Street, Norwalk, Connecticut, USA",
         "id" : "b32210f96510d3d2d4afa8a1c94dc1cb5b9150ce",
         "matched_substrings" : [
            {
               "length" : 3,
               "offset" : 0
            },
            {
               "length" : 4,
               "offset" : 4
            }
         ],
         "place_id" : "ChIJH29QPUoc6IkRLAeU4Tz_qWI",
         "reference" : "ChIJH29QPUoc6IkRLAeU4Tz_qWI",
         "structured_formatting" : {
            "main_text" : "110 Ward Street",
            "main_text_matched_substrings" : [
               {
                  "length" : 3,
                  "offset" : 0
               },
               {
                  "length" : 4,
                  "offset" : 4
               }
            ],
            "secondary_text" : "Norwalk, Connecticut, USA"
         },
         "terms" : [
            {
               "offset" : 0,
               "value" : "110"
            },
            {
               "offset" : 4,
               "value" : "Ward Street"
            },
            {
               "offset" : 17,
               "value" : "Norwalk"
            },
            {
               "offset" : 26,
               "value" : "Connecticut"
            },
            {
               "offset" : 39,
               "value" : "USA"
            }
         ],
         "types" : [ "premise", "geocode" ]
      },
      {
         "description" : "110 Ward Avenue, Staten Island, New York, USA",
         "id" : "6cc9db388d108771adeab868649df74d2927e130",
         "matched_substrings" : [
            {
               "length" : 8,
               "offset" : 0
            }
         ],
         "place_id" : "Ei0xMTAgV2FyZCBBdmVudWUsIFN0YXRlbiBJc2xhbmQsIE5ldyBZb3JrLCBVU0EiMBIuChQKEglVpSorNE7CiRFdtEQPPhmsHhBuKhQKEgmNFhXWNU7CiREpS1o_wxjjzw",
         "reference" : "Ei0xMTAgV2FyZCBBdmVudWUsIFN0YXRlbiBJc2xhbmQsIE5ldyBZb3JrLCBVU0EiMBIuChQKEglVpSorNE7CiRFdtEQPPhmsHhBuKhQKEgmNFhXWNU7CiREpS1o_wxjjzw",
         "structured_formatting" : {
            "main_text" : "110 Ward Avenue",
            "main_text_matched_substrings" : [
               {
                  "length" : 8,
                  "offset" : 0
               }
            ],
            "secondary_text" : "Staten Island, New York, USA"
         },
         "terms" : [
            {
               "offset" : 0,
               "value" : "110 Ward Avenue"
            },
            {
               "offset" : 17,
               "value" : "Staten Island"
            },
            {
               "offset" : 32,
               "value" : "New York"
            },
            {
               "offset" : 42,
               "value" : "USA"
            }
         ],
         "types" : [ "street_address", "geocode" ]
      },
      {
         "description" : "110 Wardwell Avenue, Staten Island, New York, USA",
         "id" : "2da74ee5ddd35578a31ecb30a168c8d15556a143",
         "matched_substrings" : [
            {
               "length" : 8,
               "offset" : 0
            }
         ],
         "place_id" : "EjExMTAgV2FyZHdlbGwgQXZlbnVlLCBTdGF0ZW4gSXNsYW5kLCBOZXcgWW9yaywgVVNBIjASLgoUChIJy33OrtNNwokR9tgzNi2JY-YQbioUChIJR-Dk1dJNwokR-E7Z0DswFRI",
         "reference" : "EjExMTAgV2FyZHdlbGwgQXZlbnVlLCBTdGF0ZW4gSXNsYW5kLCBOZXcgWW9yaywgVVNBIjASLgoUChIJy33OrtNNwokR9tgzNi2JY-YQbioUChIJR-Dk1dJNwokR-E7Z0DswFRI",
         "structured_formatting" : {
            "main_text" : "110 Wardwell Avenue",
            "main_text_matched_substrings" : [
               {
                  "length" : 8,
                  "offset" : 0
               }
            ],
            "secondary_text" : "Staten Island, New York, USA"
         },
         "terms" : [
            {
               "offset" : 0,
               "value" : "110 Wardwell Avenue"
            },
            {
               "offset" : 21,
               "value" : "Staten Island"
            },
            {
               "offset" : 36,
               "value" : "New York"
            },
            {
               "offset" : 46,
               "value" : "USA"
            }
         ],
         "types" : [ "street_address", "geocode" ]
      },
      {
         "description" : "110 Ward Place, South Orange, New Jersey, USA",
         "id" : "b90b144fbf95f99b6307d301d642a2d39debe7b4",
         "matched_substrings" : [
            {
               "length" : 8,
               "offset" : 0
            }
         ],
         "place_id" : "Ei0xMTAgV2FyZCBQbGFjZSwgU291dGggT3JhbmdlLCBOZXcgSmVyc2V5LCBVU0EiMBIuChQKEgkjr7I1kKzDiRHJj7ZOBIji1RBuKhQKEgk1dkQ2kKzDiRHp_pbhNlWNjw",
         "reference" : "Ei0xMTAgV2FyZCBQbGFjZSwgU291dGggT3JhbmdlLCBOZXcgSmVyc2V5LCBVU0EiMBIuChQKEgkjr7I1kKzDiRHJj7ZOBIji1RBuKhQKEgk1dkQ2kKzDiRHp_pbhNlWNjw",
         "structured_formatting" : {
            "main_text" : "110 Ward Place",
            "main_text_matched_substrings" : [
               {
                  "length" : 8,
                  "offset" : 0
               }
            ],
            "secondary_text" : "South Orange, New Jersey, USA"
         },
         "terms" : [
            {
               "offset" : 0,
               "value" : "110 Ward Place"
            },
            {
               "offset" : 16,
               "value" : "South Orange"
            },
            {
               "offset" : 30,
               "value" : "New Jersey"
            },
            {
               "offset" : 42,
               "value" : "USA"
            }
         ],
         "types" : [ "street_address", "geocode" ]
      }
   ],
   "status" : "OK"
}`

**Comment by Jeca1801** [comment]
[response.txt](https://github.com/jaing/react-native-places-input/files/4312772/response.txt)

**Comment by jaing** [comment]
Any which one is causing a trouble?

**Comment by Jeca1801** [comment]
hm i'm unsure on getting the response that i want... I'm from sweden.. and my search input is stockholm.. my latitude 59.30403924658636 and longitude 18.048340380191807. could you help me out? could you fill in these in the proper location and i'll fix the api key..

**Comment by jaing** [comment]
So in a response there is an array of places. My question is which one is causing an API error when you click it.

**Comment by Jeca1801** [comment]
when i click on a option in the predictions it says undefined is not an object ... and its pointing to place.result.formatted_adress... sometimes it happens to every one of the predictions and sometimes it doesent happend and it works fine... does this answer your question?

**Comment by jaing** [comment]
I need a place id to debug it. You send me a response with multiple places:

`{
  "predictions" : [
    {
      "description" : "110 Ward Drive, New Rochelle, New York, USA",
      "id" : "3ed4273818378bfea2b2a2ee7b5261a4403533d2",
      "matched_substrings" : [
        {
          "length" : 3,
          "offset" : 0
        },
        {
          "length" : 4,
          "offset" : 4
        }
      ],
      "place_id" : "ChIJzT6wM7OTwokR95iWmndXFP0",
      "reference" : "ChIJzT6wM7OTwokR95iWmndXFP0",
      "structured_formatting" : {
        "main_text" : "110 Ward Drive",
        "main_text_matched_substrings" : [
          {
            "length" : 3,
            "offset" : 0
          },
          {
            "length" : 4,
            "offset" : 4
          }
        ],
        "secondary_text" : "New Rochelle, New York, USA"
      },
      "terms" : [
        {
          "offset" : 0,
          "value" : "110"
        },
        {
          "offset" : 4,
          "value" : "Ward Drive"
        },
        {
          "offset" : 16,
          "value" : "New Rochelle"
        },
        {
          "offset" : 30,
          "value" : "New York"
        },
        {
          "offset" : 40,
          "value" : "USA"
        }
      ],
      "types" : [ "premise", "geocode" ]
    },
]`

I need a place_id that is causing this error. I.e. when i click "110 Ward Drive, New Rochelle, New York, USA i get an error. Or when i click on Staten Island, New York, USA.

Also please post your implementation - i.e.

`<PlacesInput language="en" />`

**Comment by Jeca1801** [comment]
https://gyazo.com/1d8015302dcd01e6dc91efba79a76499 so this is my implementations (i cut out the api key) .. this is the response i get back when using the api in my code {"html_attributions": [], "result": {"formatted_address": "Uppsala, Sweden", "geometry": {"location": [Object], "viewport": [Object]}, "name": "Uppsala"}, "status": "OK"}...  how do i provide the place_id, sir?

**Comment by jaing** [comment]
can you try 1.0.9 version?

**Comment by Jeca1801** [comment]
tried it seemed to work better but i still get this error sometimes... https://gyazo.com/278eab82fb642fd2d0e8d4f8a122bfee

**Comment by Jeca1801** [comment]
it's weird because it works alot of the times for the same one..

**Comment by jaing** [comment]
Yes it is weird. If you change your onSelect method to console.log(place) not setState and see if it works? Looks like a problem is on your end since i added a safe check in a new version:

place && place.result && (place.result.formatted_address || place.result.name),

**Comment by Jeca1801** [comment]
i still get the same error even if i log it

**Comment by jaing** [comment]
Sorry but this is technically impossible. There is only one palce in a code in current version where I'm referring to a formatted_address and there is a safe check for that (place && place.result && (place.result.formatted_address || place.result.name),). Maybe you can clear you node modules and reinstall a package.
