### ISSUE TITLE
Restricting to search only locality/administrative_area_level_3

### ISSUE THREAD

**Issue by adarshperumal** [jaing/react-native-places-input#4]
Is there a provision to look up only for locality ?

**Comment by jaing** [comment]
Done. I updated a readme and changelog:

## 1.0.10
New configuration props:
* **queryTypes** - You may restrict results from a Place Autocomplete request to be of a certain type by passing a types parameter.

### Place types
```javascript
    <PlacesInput
        placeHolder={'Some placeholder'}
        queryTypes="establishment"
        googleApiKey={GOOGLE_API_KEY} 
        onSelect={place => this.setState({place})} 
    />
```

https://developers.google.com/places/web-service/autocomplete#place_types
