### ISSUE TITLE
Current location

### ISSUE THREAD

**Issue by Deboracgs** [jaing/react-native-places-input#5]
Any update to get current location?

**Comment by jaing** [comment]
Do we need it? There are few different ways to get a current location in React Native (using expo or different packages). I don't think this component should force a way to get it. Another issue with that is that a user location is defined using cords (lat,lng). To decode it you will need to use a google reverse geocoding API (that is expensive compared to autocomplete / places API). 


> MONTHLY VOLUME RANGE(Price per REQUEST)
> --
> 0–100,000 | 100,001–500,000 | 500,000+
> 0.005 USD per each(5.00 USD per 1000) | 0.004 USD per each(4.00 USD per 1000) | Contact Sales for volume pricing
> 
> 

What I can do is i can add a prop where you can pass a user location from a parent component and my component can do a geocoding call (if you google API key is allowed to use this API) and set a current location in an input field. Thoughts?
