### ISSUE TITLE
Results list not showing

### ISSUE THREAD

**Issue by smohit02** [jaing/react-native-places-input#6]
As soon as I finish typing, the activity loader comes and disappears within a second,
and no results show up.
What am I doing wrong here?
This was the case with the other Google places libraries like "react-native-google-autocomplete" and "react-native-google-places-autocomplete"

My API key seems to be working fine as I am able to retrieve the results using the API URL in the browser.

I found your library recently and decided to use it after using all possible and available libraries with no success and exactly the same issue.
Any help would be appreciated!

**Comment by aniruddhbhamare** [comment]
Same Problem

**Comment by jaing** [comment]
Can you paste your implementation and what device you are testing? 
Do you see a results in a browser if you use this url:

https://maps.googleapis.com/maps/api/place/autocomplete/json?input=Vict&key=YOUR_API_KEY

**Comment by sergiokopplin** [comment]
Hey @smohit02, @aniruddhbhamare. It's working fine here. Just installed.
It was not working because I was trying to get portuguese results with the english language as a prop. Now it's fine!

**Comment by smohit02** [comment]
> Can you paste your implementation and what device you are testing?
> Do you see a results in a browser if you use this url:
> 
> https://maps.googleapis.com/maps/api/place/autocomplete/json?input=Vict&key=YOUR_API_KEY

I just tried with your given API link, I'm getting an error:

**"You must enable Billing on the Google Cloud Project at https://console.cloud.google.com/project/_/billing/enable Learn more at https://developers.google.com/maps/gmp-get-started"**

Does this need billing enabled?


**My Implementation:**

```
import React, { Component } from 'react';
import { View, Dimensions, TextInput, ScrollView, StyleSheet, TouchableOpacity, Text, Modal, Button, ActivityIndicator } from 'react-native'
import Ionicons from 'react-native-vector-icons/Ionicons';
import MapView from 'react-native-maps';
import PlacesInput from 'react-native-places-input';

const { height, width } = Dimensions.get('screen');
const SCREEN_HEIGHT = height
const SCREEN_WIDTH = width
const ASPECT_RATIO = width / height
const LATITUDE_DELTA = 0.006

const myKEY = `AIz.............E4`

export default class NewSearch extends Component {
    render() {
        return (
            <View style={styles.mainContainer}>

                <MapView
                    initialRegion={{
                        latitude: 47.985795,
                        longitude: 21.550754,
                        latitudeDelta: 0.6,
                        longitudeDelta: 0.4,
                    }}

                    style={styles.map}
                    showsMyLocationButton={true}
                    showsUserLocation={true}
                />

                <PlacesInput
                    googleApiKey={myKEY}
                    placeHolder={"Some Place holder"}
                    language={"en-US"}
                    requiredTimeBeforeSearch={2000}
                    onSelect={place => {
                        this.props.goToPoint(get(place, 'result.geometry.location.lat'), get(place, 'result.geometry.location.lng'))
                    }}
                    iconResult={<Ionicons name="md-pin" size={25} style={styles.placeIcon} />}
                />
            </View>
        );
    }
}

const styles = StyleSheet.create({
    container: {
        position: 'absolute',
        top: 10,
        left: 10,
        right: 10,
        zIndex: 1000,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,

        elevation: 5,
    },

    mainContainer: {
        flex: 1,
        position: "absolute",
        height: '100%',
        width: '100%',
        backgroundColor: 'white'
    },

    map: {
        position: 'absolute',
        height: SCREEN_HEIGHT,
        width: SCREEN_WIDTH,
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        // display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-between'
    },

    input: {
        height: 50,
        backgroundColor: '#fff',
        paddingHorizontal: 15,
    },
    scrollView: {
        backgroundColor: '#fff',
    },
    place: {
        flexDirection: 'row',
        borderBottomWidth: 1,
        borderColor: 'rgba(0,0,0,0.1)',
        padding: 15,
        position: 'relative',
        zIndex: 10001,
    },
    placeIcon: {
        position: 'absolute',
        top: 10,
        right: 15,
        color: 'rgba(0,0,0,0.3)',
    },
    placeText: {
        color: 'rgba(0,0,0,0.8)',
        paddingRight: 60,
    },
    loading: {
        margin: 10,
    },
});

```

![MyImplementation](https://user-images.githubusercontent.com/32566226/76907971-9ecc6080-68cd-11ea-88cb-ed4d2df89c61.gif)

**Comment by jaing** [comment]
Yep this API has a free quota but you need to have a Google Billing account added to use it. Simply add a credit card into your account and it will be working fine.

**Comment by augustosamame** [comment]
In my case the error being seen when using the web link test was: 
{
   "error_message" : "API keys with referer restrictions cannot be used with this API.",
   "predictions" : [],
   "status" : "REQUEST_DENIED"
}

I created an additional API key with no restrictions and it started working fine.

**Comment by scriptpapi** [comment]
Make sure to have "Places API" enabled for your project.
